export const GET_ALL_JOBPOSTED_SUCCESS ='GET_ALL_JOBPOSTED_SUCCESS';
export const GET_ALL_JOBPOSTED_FAILED ='GET_ALL_JOBPOSTED_FAILED';
export const CREATE_JOBPOSTED_SUCCESS ='CREATE_JOBPOSTED_SUCCESS';
export const CREATE_JOBPOSTED_FAILED ='CREATE_JOBPOSTED_FAILED';